#! /bin/bash
# xpack="path/to/xpack/"
# pypath="path/to/pypy/"
export XPACK=$(cat xpackpath)
alias pypath=$(cat pypath)

alias run="pypath perf_model/run.py"
alias runall="run perf_model/compilation/build"

cd perf_model/compilation/
make clean
make
cd ../..
